# Data Cleaning and Preprocessing

In [14]:
# Import Libraries

import pandas as pd
import numpy as np

In [69]:
#Load Data

df = pd.read_csv("dirty_cafe_sales.csv")

Initial Inspection

In [70]:
# Display first five row

df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [25]:
# Display last five row

df.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [27]:
#Data Types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [23]:
# Describe data
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,9667,9862,9821,9827,7421,6735,9841
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1171,2013,2429,979,2291,3022,159

# Data Cleaning

In [29]:
# Check for missing value

df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

Fill missing categorical data with unknown(location, payment method, item)

In [50]:
df['Location'] = df['Location'].fillna('Unknown')
df['Payment Method'] = df['Payment Method'].fillna('Unknown')
df['Item'] = df['Item'].fillna('Unknown')

print(' categorical columns fixed and filled')

 categorical columns fixed and filled






change  the data type of quantity, price per unit and total spent to numeric before filling

In [72]:
# Change data formart of Quantity, Price and Total Spent to numeric
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors = 'coerce')

In [73]:
# fill the missing values in quantity and price column  with the median to preserve data size
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].median())
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Price Per Unit'].median())

In [74]:
# fill Total Spent from quantity and price using total spent = quantity * price per unit
df['Total Spent'] = df['Total Spent'].fillna(df['Quantity'] * df['Price Per Unit'])

In [51]:
print( 'numeric column fixed and filled')

numeric column fixed and filled

Clean the date column

In [53]:
# Convert to datetime
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')

In [56]:
# Drop rows where the date is still missing
df.dropna(subset=['Transaction Date'], inplace=True)

print(' date column fixed and filled')

 date column fixed and filled

In [62]:
# Rename Column

df.columns = df.columns.str.lower().str.replace(" ", "_")

Final check

In [64]:
df.isnull().sum()

transaction_id      0
item                0
quantity            0
price_per_unit      0
total_spent         0
payment_method      0
location            0
transaction_date    0
dtype: int64

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9540 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    9540 non-null   object
 1   item              9540 non-null   object
 2   quantity          9540 non-null   float64
 3   price_per_unit    9540 non-null   float64
 4   total_spent       9540 non-null   float64
 5   payment_method    9540 non-null   object
 6   location          9540 non-null   object
 7   transaction_date  9540 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 670.8+ KB

In [67]:
print('data cleaned successfully')

data cleaned successfully

In [68]:
# save cleaned data

df.to_csv("cleaned_cafe_sales.csv", index=False)